/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlado;

import javax.swing.JOptionPane;
 import vista.*;
/**
 *
 * @author Usuario
 */
public class MDItour_operadora extends javax.swing.JFrame {

    private InternalFrameCliente cliente;
    private InternalFrameEmpleado empleado;
    private InternalFrameGira gira;
    private InternalFrameParticipante participante;
    private InternalFrameReserva reserva;
    private Bienvenida bienvenida;
    /**
     * Creates new form MDItour_operadora
     */
    public MDItour_operadora() {
        initComponents();
        setTitle("Tour Operadora");
        cliente = new InternalFrameCliente();
        desktopPane1.add(cliente);
        empleado = new InternalFrameEmpleado();
        desktopPane1.add(empleado);
        gira = new InternalFrameGira();
        desktopPane1.add(gira);
        participante = new InternalFrameParticipante();
        desktopPane1.add(participante);
        reserva = new InternalFrameReserva();
        desktopPane1.add(reserva);
        bienvenida = new Bienvenida();
        desktopPane1.add(bienvenida);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        desktopPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnVerGira = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnVerCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnVerReservacion = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnVerParticipantes = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnVerEmpleados = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuBienvenida = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(MDItour_operadora.MAXIMIZED_BOTH);

        javax.swing.GroupLayout desktopPane1Layout = new javax.swing.GroupLayout(desktopPane1);
        desktopPane1.setLayout(desktopPane1Layout);
        desktopPane1Layout.setHorizontalGroup(
            desktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        desktopPane1Layout.setVerticalGroup(
            desktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Accesos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(0, 153, 153))); // NOI18N

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnVerGira.setBackground(new java.awt.Color(255, 255, 255));
        btnVerGira.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVerGira.setForeground(new java.awt.Color(0, 102, 102));
        btnVerGira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/montana.png"))); // NOI18N
        btnVerGira.setText("Giras               ");
        btnVerGira.setFocusable(false);
        btnVerGira.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVerGira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerGiraActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVerGira);
        jToolBar1.add(jSeparator2);

        btnVerCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnVerCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVerCliente.setForeground(new java.awt.Color(0, 102, 102));
        btnVerCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base-de-datos.png"))); // NOI18N
        btnVerCliente.setText("Cliente            ");
        btnVerCliente.setFocusable(false);
        btnVerCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVerCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerClienteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVerCliente);
        jToolBar1.add(jSeparator1);

        btnVerReservacion.setBackground(new java.awt.Color(255, 255, 255));
        btnVerReservacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVerReservacion.setForeground(new java.awt.Color(0, 102, 102));
        btnVerReservacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reservacion-en-linea.png"))); // NOI18N
        btnVerReservacion.setText("Reservacion   ");
        btnVerReservacion.setFocusable(false);
        btnVerReservacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVerReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReservacionActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVerReservacion);
        jToolBar1.add(jSeparator3);

        btnVerParticipantes.setBackground(new java.awt.Color(255, 255, 255));
        btnVerParticipantes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVerParticipantes.setForeground(new java.awt.Color(0, 102, 102));
        btnVerParticipantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diversidad.png"))); // NOI18N
        btnVerParticipantes.setText("Participantes  ");
        btnVerParticipantes.setFocusable(false);
        btnVerParticipantes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVerParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerParticipantesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVerParticipantes);
        jToolBar1.add(jSeparator4);

        btnVerEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        btnVerEmpleados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVerEmpleados.setForeground(new java.awt.Color(0, 102, 102));
        btnVerEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/servicio-al-cliente.png"))); // NOI18N
        btnVerEmpleados.setText("Empleados      ");
        btnVerEmpleados.setFocusable(false);
        btnVerEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVerEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEmpleadosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVerEmpleados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        desktopPane.setLayer(desktopPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane1))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Acerca de");

        menuBienvenida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/servicio-al-cliente.png"))); // NOI18N
        menuBienvenida.setText("Bienvenido");
        menuBienvenida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBienvenidaActionPerformed(evt);
            }
        });
        jMenu1.add(menuBienvenida);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerGiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerGiraActionPerformed
        // TODO add your handling code here:
        gira.obtenerDatos();
        gira.setVisible(true);
    }//GEN-LAST:event_btnVerGiraActionPerformed

    private void btnVerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerClienteActionPerformed
        // TODO add your handling code here:
        cliente.obtenerDatos();
        cliente.setVisible(true);
    }//GEN-LAST:event_btnVerClienteActionPerformed

    private void btnVerReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReservacionActionPerformed
        // TODO add your handling code here:
        reserva.obtenerDatos();
        reserva.setVisible(true);
    }//GEN-LAST:event_btnVerReservacionActionPerformed

    private void btnVerParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerParticipantesActionPerformed
        // TODO add your handling code here:
        participante.obtenerDatos();
        participante.setVisible(true);
    }//GEN-LAST:event_btnVerParticipantesActionPerformed

    private void btnVerEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEmpleadosActionPerformed
        // TODO add your handling code here:
        empleado.obtenerDatos();
        empleado.setVisible(true);
    }//GEN-LAST:event_btnVerEmpleadosActionPerformed

    private void menuBienvenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBienvenidaActionPerformed
        // TODO add your handling code here:
        bienvenida.setVisible(true);
    }//GEN-LAST:event_menuBienvenidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDItour_operadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDItour_operadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDItour_operadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDItour_operadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDItour_operadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerCliente;
    private javax.swing.JButton btnVerEmpleados;
    private javax.swing.JButton btnVerGira;
    private javax.swing.JButton btnVerParticipantes;
    private javax.swing.JButton btnVerReservacion;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLayeredPane desktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuBienvenida;
    // End of variables declaration//GEN-END:variables

}
