/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlador;
import vista.*;


/**
 *
 * @author Kentry Gutter
 */
public class TourMDIOperadora extends javax.swing.JFrame {

    private InternalFrameGiras registroGiras;
    private InternalFrameCliente Cliente;
    private InternalFrameEmpleados Empleados;
    private InternalFrameReservas Reservas;
    private InternalFrameParticipantes Participantes;
    /**
     * Creates new form TourMDIOperadora
     */
    public TourMDIOperadora() {
        initComponents();
        setTitle("TOUR OPERADORA");
        registroGiras = new InternalFrameGiras();
        desktopPane.add(registroGiras);
        
        Cliente = new InternalFrameCliente();
        desktopPane.add(Cliente);
        
        Empleados = new InternalFrameEmpleados();
        desktopPane.add(Empleados);
        
        Reservas = new InternalFrameReservas();
        desktopPane.add(Reservas);
        
        Participantes = new InternalFrameParticipantes();
        desktopPane.add(Participantes);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator7 = new javax.swing.JSeparator();
        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnVentanaGira = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnVentanaClientes = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnVentanaEmpleados = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnVentanaReservas = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnVentanaParticipantes = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuGira = new javax.swing.JMenu();
        menuitemGira = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(TourMDIOperadora.MAXIMIZED_BOTH);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Accesos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 153))); // NOI18N

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        btnVentanaGira.setBackground(new java.awt.Color(255, 255, 255));
        btnVentanaGira.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVentanaGira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/montana.png"))); // NOI18N
        btnVentanaGira.setText("Gira                 ");
        btnVentanaGira.setFocusPainted(false);
        btnVentanaGira.setFocusable(false);
        btnVentanaGira.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnVentanaGira.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVentanaGira.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnVentanaGira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaGiraActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVentanaGira);
        jToolBar1.add(jSeparator2);

        btnVentanaClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnVentanaClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVentanaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base-de-datos.png"))); // NOI18N
        btnVentanaClientes.setText("Clientes           ");
        btnVentanaClientes.setFocusPainted(false);
        btnVentanaClientes.setFocusable(false);
        btnVentanaClientes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVentanaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVentanaClientes);
        jToolBar1.add(jSeparator1);

        btnVentanaEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        btnVentanaEmpleados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVentanaEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/servicio-al-cliente.png"))); // NOI18N
        btnVentanaEmpleados.setText("Empleados      ");
        btnVentanaEmpleados.setFocusPainted(false);
        btnVentanaEmpleados.setFocusable(false);
        btnVentanaEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVentanaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaEmpleadosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVentanaEmpleados);
        jToolBar1.add(jSeparator3);

        btnVentanaReservas.setBackground(new java.awt.Color(255, 255, 255));
        btnVentanaReservas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVentanaReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reservacion-en-linea.png"))); // NOI18N
        btnVentanaReservas.setText("Reservaciones");
        btnVentanaReservas.setFocusPainted(false);
        btnVentanaReservas.setFocusable(false);
        btnVentanaReservas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVentanaReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaReservasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVentanaReservas);
        jToolBar1.add(jSeparator4);

        btnVentanaParticipantes.setBackground(new java.awt.Color(255, 255, 255));
        btnVentanaParticipantes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVentanaParticipantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diversidad.png"))); // NOI18N
        btnVentanaParticipantes.setText("Participantes   ");
        btnVentanaParticipantes.setFocusable(false);
        btnVentanaParticipantes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnVentanaParticipantes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVentanaParticipantes.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnVentanaParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaParticipantesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVentanaParticipantes);
        jToolBar1.add(jSeparator5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pat'e Perro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 3, 18), new java.awt.Color(204, 255, 255))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuGira.setText("Acerca de");

        menuitemGira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/servicio-al-cliente.png"))); // NOI18N
        menuitemGira.setText("Desarrolladores");
        menuGira.add(menuitemGira);

        jMenuBar1.add(menuGira);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentanaReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaReservasActionPerformed
        // TODO add your handling code here:
        Reservas.obtenerDatos();
        Reservas.setVisible(true);
       
    }//GEN-LAST:event_btnVentanaReservasActionPerformed

    private void btnVentanaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaEmpleadosActionPerformed
        // TODO add your handling code here:
        Empleados.obtenerDatos();
        Empleados.setVisible(true);
    }//GEN-LAST:event_btnVentanaEmpleadosActionPerformed

    private void btnVentanaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaClientesActionPerformed
        // TODO add your handling code here:
        Cliente.obtenerDatos();
        Cliente.setVisible(true);
    }//GEN-LAST:event_btnVentanaClientesActionPerformed

    private void btnVentanaGiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaGiraActionPerformed
        // TODO add your handling code here:
        registroGiras.obtenerDatos();
        registroGiras.setVisible(true);
    }//GEN-LAST:event_btnVentanaGiraActionPerformed

    private void btnVentanaParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaParticipantesActionPerformed
        // TODO add your handling code here:
        Participantes.obtenerDatos();
        Participantes.setVisible(true);
    }//GEN-LAST:event_btnVentanaParticipantesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TourMDIOperadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TourMDIOperadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TourMDIOperadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TourMDIOperadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TourMDIOperadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVentanaClientes;
    private javax.swing.JButton btnVentanaEmpleados;
    private javax.swing.JButton btnVentanaGira;
    private javax.swing.JButton btnVentanaParticipantes;
    private javax.swing.JButton btnVentanaReservas;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuGira;
    private javax.swing.JMenuItem menuitemGira;
    // End of variables declaration//GEN-END:variables

}
