/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlador;

import vista.*;


/**
 *
 * @author Kentry Gutter
 */
public class TourMDIOperadora extends javax.swing.JFrame {

    private InternalFrameEmpleados Empleados;
    private IntenalFrameGira Giras;
    private InternalFrameParticipante Participante;
    private InternalFrameReservas Reservas;
    /**
     * Creates new form TourMDIOperadora
     */
    public TourMDIOperadora() {
        initComponents();
        Empleados = new InternalFrameEmpleados();
        desktopPane.add(Empleados);
        Giras = new IntenalFrameGira();
        desktopPane.add(Giras);
        Participante = new InternalFrameParticipante();
        desktopPane.add(Participante);
        Reservas = new InternalFrameReservas();
        desktopPane.add(Reservas);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnVentanaGira = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnVentanaParticipante = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnVentanaEmpleados = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnVentanaReservas = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(TourMDIOperadora.MAXIMIZED_BOTH);

        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        btnVentanaGira.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVentanaGira.setForeground(new java.awt.Color(0, 0, 255));
        btnVentanaGira.setText("Registrar Giras");
        btnVentanaGira.setFocusPainted(false);
        btnVentanaGira.setFocusable(false);
        btnVentanaGira.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentanaGira.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVentanaGira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaGiraActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVentanaGira);
        jToolBar1.add(jSeparator2);

        btnVentanaParticipante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVentanaParticipante.setForeground(new java.awt.Color(0, 0, 255));
        btnVentanaParticipante.setText("Registrar Participante");
        btnVentanaParticipante.setFocusPainted(false);
        btnVentanaParticipante.setFocusable(false);
        btnVentanaParticipante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentanaParticipante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVentanaParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaParticipanteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVentanaParticipante);
        jToolBar1.add(jSeparator1);

        btnVentanaEmpleados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVentanaEmpleados.setForeground(new java.awt.Color(0, 0, 255));
        btnVentanaEmpleados.setText("Registrar Empleados");
        btnVentanaEmpleados.setFocusPainted(false);
        btnVentanaEmpleados.setFocusable(false);
        btnVentanaEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentanaEmpleados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVentanaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaEmpleadosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVentanaEmpleados);
        jToolBar1.add(jSeparator3);

        btnVentanaReservas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVentanaReservas.setForeground(new java.awt.Color(0, 0, 255));
        btnVentanaReservas.setText("Registrar Reservas");
        btnVentanaReservas.setFocusPainted(false);
        btnVentanaReservas.setFocusable(false);
        btnVentanaReservas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentanaReservas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVentanaReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaReservasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVentanaReservas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        desktopPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 809, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void btnVentanaReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaReservasActionPerformed
        // TODO add your handling code here:
        Reservas.setVisible(true);
       
    }//GEN-LAST:event_btnVentanaReservasActionPerformed

    private void btnVentanaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaEmpleadosActionPerformed
        // TODO add your handling code here:
        Empleados.setVisible(true);
    }//GEN-LAST:event_btnVentanaEmpleadosActionPerformed

    private void btnVentanaParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaParticipanteActionPerformed
        // TODO add your handling code here:
        Participante.setVisible(true);
    }//GEN-LAST:event_btnVentanaParticipanteActionPerformed

    private void btnVentanaGiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaGiraActionPerformed
        // TODO add your handling code here:
        Giras.setVisible(true);
    }//GEN-LAST:event_btnVentanaGiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TourMDIOperadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TourMDIOperadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TourMDIOperadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TourMDIOperadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TourMDIOperadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton btnVentanaEmpleados;
    private javax.swing.JButton btnVentanaGira;
    private javax.swing.JButton btnVentanaParticipante;
    private javax.swing.JButton btnVentanaReservas;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
