/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlador;

import javax.swing.plaf.DesktopPaneUI;
import vista.*;


/**
 *
 * @author Kentry Gutter
 */
public class TourMDIOperadora extends javax.swing.JFrame {

    private InternalFrameGiras Giras;
    private InternalFrameCliente Cliente;
    private InternalFrameEmpleados Empleados;
    private InternalFrameReservas Reservas;
    private InternalFrameParticipantes Participantes;
    /**
     * Creates new form TourMDIOperadora
     */
    public TourMDIOperadora() {
        initComponents();
        setTitle("TOUR OPERADORA Pat e Perro");
//        Giras = new InternalFrameGiras();
//        desktopPane.add(Giras);
        
        Cliente = new InternalFrameCliente();
        desktopPane.add(Cliente);
        
        Empleados = new InternalFrameEmpleados();
        desktopPane.add(Empleados);
        
        Reservas = new InternalFrameReservas();
        desktopPane.add(Reservas);
        
        Participantes = new InternalFrameParticipantes();
        desktopPane.add(Participantes);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator7 = new javax.swing.JSeparator();
        desktopPane = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnVentanaGira = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnVentanaClientes = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnVentanaEmpleados = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnVentanaReservas = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnVentanaParticipantes = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(TourMDIOperadora.MAXIMIZED_BOTH);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        btnVentanaGira.setBackground(new java.awt.Color(255, 255, 255));
        btnVentanaGira.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVentanaGira.setForeground(new java.awt.Color(0, 0, 255));
        btnVentanaGira.setText("Gira");
        btnVentanaGira.setFocusPainted(false);
        btnVentanaGira.setFocusable(false);
        btnVentanaGira.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentanaGira.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVentanaGira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaGiraActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVentanaGira);
        jToolBar1.add(jSeparator2);

        btnVentanaClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnVentanaClientes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVentanaClientes.setForeground(new java.awt.Color(0, 0, 255));
        btnVentanaClientes.setText("Clientes");
        btnVentanaClientes.setFocusPainted(false);
        btnVentanaClientes.setFocusable(false);
        btnVentanaClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentanaClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVentanaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVentanaClientes);
        jToolBar1.add(jSeparator1);

        btnVentanaEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        btnVentanaEmpleados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVentanaEmpleados.setForeground(new java.awt.Color(0, 0, 255));
        btnVentanaEmpleados.setText("Empleados");
        btnVentanaEmpleados.setFocusPainted(false);
        btnVentanaEmpleados.setFocusable(false);
        btnVentanaEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentanaEmpleados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVentanaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaEmpleadosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVentanaEmpleados);
        jToolBar1.add(jSeparator3);

        btnVentanaReservas.setBackground(new java.awt.Color(255, 255, 255));
        btnVentanaReservas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVentanaReservas.setForeground(new java.awt.Color(0, 0, 255));
        btnVentanaReservas.setText("Reservaciones");
        btnVentanaReservas.setFocusPainted(false);
        btnVentanaReservas.setFocusable(false);
        btnVentanaReservas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVentanaReservas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVentanaReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaReservasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVentanaReservas);
        jToolBar1.add(jSeparator4);

        btnVentanaParticipantes.setBackground(new java.awt.Color(255, 255, 255));
        btnVentanaParticipantes.setForeground(new java.awt.Color(0, 51, 255));
        btnVentanaParticipantes.setText("Participantes");
        btnVentanaParticipantes.setFocusable(false);
        btnVentanaParticipantes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentanaParticipantes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVentanaParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaParticipantesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVentanaParticipantes);
        jToolBar1.add(jSeparator5);

        desktopPane.setLayer(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 532, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenu1.add(jSeparator6);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentanaReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaReservasActionPerformed
        // TODO add your handling code here:
        Reservas.obtenerDatos();
        Reservas.setVisible(true);
       
    }//GEN-LAST:event_btnVentanaReservasActionPerformed

    private void btnVentanaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaEmpleadosActionPerformed
        // TODO add your handling code here:
        Empleados.obtenerDatos();
        Empleados.setVisible(true);
    }//GEN-LAST:event_btnVentanaEmpleadosActionPerformed

    private void btnVentanaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaClientesActionPerformed
        // TODO add your handling code here:
        Cliente.obtenerDatos();
        Cliente.setVisible(true);
    }//GEN-LAST:event_btnVentanaClientesActionPerformed

    private void btnVentanaGiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaGiraActionPerformed
        // TODO add your handling code here:
        Giras = new InternalFrameGiras();
        desktopPane.add(Giras);
        Giras.obtenerDatos();
        Giras.setVisible(true);
    }//GEN-LAST:event_btnVentanaGiraActionPerformed

    private void btnVentanaParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaParticipantesActionPerformed
        // TODO add your handling code here:
        Participantes.obtenerDatos();
        Participantes.setVisible(true);
    }//GEN-LAST:event_btnVentanaParticipantesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TourMDIOperadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TourMDIOperadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TourMDIOperadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TourMDIOperadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TourMDIOperadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVentanaClientes;
    private javax.swing.JButton btnVentanaEmpleados;
    private javax.swing.JButton btnVentanaGira;
    private javax.swing.JButton btnVentanaParticipantes;
    private javax.swing.JButton btnVentanaReservas;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
