/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Modelo.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class InternalFrameGira extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrameGira
     */
    public InternalFrameGira() {
        initComponents();
        setTitle("Registrar Giras");
        jtxtIdGira.setEnabled(false);
      
    }
    //Metodo para limpiar los campos.
    public void LimpiarCampos() {
        jtxtIdGira.setText("");
        jtxtNombreGira.setText("");
        jtxtDistanciaGira.setText("");
        jtxtPrecioGira.setText("");
        jtxtFechaGira.setText("");
        jtxtEncargado.setText("");
    }

    //Metodo para listar datos dentro de la tabla.
    public void obtenerDatos() {
        //Se crea un lista que almacena los datos obtenidos.
        List<Gira> gira = new DAOGIRA().ObtenerDatos();
        //Define un modelo para la tabla.
        DefaultTableModel modelo = new DefaultTableModel();
        //Arreglo con nombre de caolumnas de la tabla.
        String[] columnas = {"Id_gira", "Nombre Gira", 
            "Precio Gira",
            "Distancia Gira", 
            "Fecha Gira", 
            "id_Encargado"};
        //Establece los nombres definidos de las columnas.
        modelo.setColumnIdentifiers(columnas);
        for (Gira gs : gira) {
            String[] renglon = {Integer.toString(gs.getID_GIRA()),
                gs.getNOMBRE_GIRA(),
                Double.toString(gs.getPRECIO_GIRA()),
                Double.toString(gs.getDISTANCIA_GIRA()),
                gs.getFECHA_GIRA().toString(),
                Integer.toString(gs.getID_EMPLEADO())};
            modelo.addRow(renglon);
            }
                JTableGiras.setModel(modelo);
        }
    

    public void actualizarGira() {
        int id = Integer.parseInt(this.jtxtIdGira.getText());
        String nomG = this.jtxtNombreGira.getText();
        double precG = Double.parseDouble(this.jtxtPrecioGira.getText());
        double disG = Double.parseDouble(this.jtxtDistanciaGira.getText());
        Date fecG = Date.valueOf(this.jtxtFechaGira.getText());
        int id_emp = Integer.parseInt(this.jtxtEncargado.getText());

        DAOGIRA daoG = new DAOGIRA();
        int res = daoG.Actualizar(id, nomG, precG, disG, fecG,id_emp);
        if (res == 1) {
            JOptionPane.showMessageDialog(rootPane, "Gira Actualizada.");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Ocurrio un ERROR");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnAgregarGira = new javax.swing.JButton();
        btnEditarGira = new javax.swing.JButton();
        btnActualizarGira = new javax.swing.JButton();
        btnBorrarGira = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtIdGira = new javax.swing.JTextField();
        jtxtNombreGira = new javax.swing.JTextField();
        jtxtPrecioGira = new javax.swing.JTextField();
        jtxtEncargado = new javax.swing.JTextField();
        jtxtFechaGira = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jtxtDistanciaGira = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableGiras = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setResizable(true);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        btnAgregarGira.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAgregarGira.setText("Agregar");
        btnAgregarGira.setMaximumSize(new java.awt.Dimension(83, 23));
        btnAgregarGira.setMinimumSize(new java.awt.Dimension(83, 23));
        btnAgregarGira.setPreferredSize(new java.awt.Dimension(79, 23));
        btnAgregarGira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarGiraActionPerformed(evt);
            }
        });

        btnEditarGira.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditarGira.setText("Editar");
        btnEditarGira.setMaximumSize(new java.awt.Dimension(83, 23));
        btnEditarGira.setMinimumSize(new java.awt.Dimension(83, 23));
        btnEditarGira.setPreferredSize(new java.awt.Dimension(79, 23));
        btnEditarGira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarGiraActionPerformed(evt);
            }
        });

        btnActualizarGira.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnActualizarGira.setText("Actualizar");
        btnActualizarGira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarGiraActionPerformed(evt);
            }
        });

        btnBorrarGira.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBorrarGira.setText("Borrar");
        btnBorrarGira.setPreferredSize(new java.awt.Dimension(79, 23));
        btnBorrarGira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarGiraActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(btnBorrarGira, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizarGira)
                .addGap(18, 18, 18)
                .addComponent(btnEditarGira, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarGira, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBorrarGira, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarGira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditarGira, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(btnActualizarGira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giras", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Distancia");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Precio");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("ID Empleado");

        jtxtIdGira.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtNombreGira.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtNombreGira.setToolTipText("Nombre de la Gira.");

        jtxtPrecioGira.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtPrecioGira.setToolTipText("Precio de la Gira.");

        jtxtEncargado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtEncargado.setToolTipText("ID del Empleado que organiza la Gira.");

        jtxtFechaGira.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtFechaGira.setToolTipText("Año / Mes / Dia");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Fecha");

        jtxtDistanciaGira.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtDistanciaGira.setToolTipText("Distancia de la Gira en KM.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtxtNombreGira)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jtxtIdGira, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(jtxtEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jtxtFechaGira))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtxtPrecioGira, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(30, 30, 30)
                                        .addComponent(jtxtDistanciaGira, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtIdGira, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtNombreGira, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jtxtFechaGira, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtDistanciaGira, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jtxtPrecioGira, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(32, 32, 32))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giras Registradas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel3.setLayout(new javax.swing.OverlayLayout(jPanel3));

        JTableGiras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(JTableGiras);

        jPanel3.add(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarGiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarGiraActionPerformed
        // TODO add your handling code here:
        String gir = jtxtNombreGira.getText();
        String prec = jtxtPrecioGira.getText();
        String dist = jtxtDistanciaGira.getText();
        String fechG = jtxtFechaGira.getText();
        String id_empl = jtxtEncargado.getText();

        if (gir.contentEquals("") || prec.contentEquals("")
            || dist.contentEquals("") || fechG.contentEquals("")||id_empl.contentEquals("")) {
            JOptionPane.showMessageDialog(rootPane, "Todos los campos son obligatorios.");
        } else {
            try {
                Date fechg = Date.valueOf(fechG);
                double precio = Double.valueOf(prec);
                double distanci = Double.valueOf(dist);
                int id_emple = Integer.valueOf(id_empl);
                Gira gs = new DAOGIRA().Insertar(gir, precio, distanci, fechg, id_emple);
                JOptionPane.showMessageDialog(rootPane, "Registro agregado.");
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "No se agrego al registro.");
            }
        }
        obtenerDatos();
        LimpiarCampos();
    }//GEN-LAST:event_btnAgregarGiraActionPerformed

    private void btnEditarGiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarGiraActionPerformed
        // TODO add your handling code here:
        int fila = this.JTableGiras.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla.");
        } else {
            try {
                int id = Integer.parseInt((String) this.JTableGiras.getValueAt(fila, 0).toString());
                String nomG = (String) this.JTableGiras.getValueAt(fila, 1);
                double precG = Double.parseDouble((String) this.JTableGiras.getValueAt(fila, 2).toString());
                double distG = Double.parseDouble((String) this.JTableGiras.getValueAt(fila, 3).toString());
                Date fecG = Date.valueOf((String) this.JTableGiras.getValueAt(fila, 4).toString());
                int id_emp = Integer.parseInt((String) this.JTableGiras.getValueAt(fila, 5).toString());

                jtxtIdGira.setText("" + id);
                jtxtNombreGira.setText(nomG);
                jtxtPrecioGira.setText(String.valueOf(precG));
                jtxtDistanciaGira.setText(String.valueOf(distG));
                jtxtFechaGira.setText(String.valueOf(fecG));
                jtxtEncargado.setText(String.valueOf(id_emp));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnEditarGiraActionPerformed

    private void btnActualizarGiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarGiraActionPerformed
        // TODO add your handling code here:
        actualizarGira();
        obtenerDatos();
        LimpiarCampos();
    }//GEN-LAST:event_btnActualizarGiraActionPerformed

    private void btnBorrarGiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarGiraActionPerformed
        // TODO add your handling code here:
        int fila = this.JTableGiras.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione unregistro de la tabla.");
        } else {
            int id = Integer.parseInt((String) this.JTableGiras.getValueAt(fila, 0).toString());
            DAOGIRA dao = new DAOGIRA();
            dao.Eliminar(id);
            obtenerDatos();
        }
    }//GEN-LAST:event_btnBorrarGiraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableGiras;
    private javax.swing.JButton btnActualizarGira;
    private javax.swing.JButton btnAgregarGira;
    private javax.swing.JButton btnBorrarGira;
    private javax.swing.JButton btnEditarGira;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jtxtDistanciaGira;
    private javax.swing.JTextField jtxtEncargado;
    private javax.swing.JTextField jtxtFechaGira;
    private javax.swing.JTextField jtxtIdGira;
    private javax.swing.JTextField jtxtNombreGira;
    private javax.swing.JTextField jtxtPrecioGira;
    // End of variables declaration//GEN-END:variables
}
