/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class InternalFrameParticipantes extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrameParticipantes
     */
    public InternalFrameParticipantes() {
        initComponents();
        setTitle("Participantes");
        jtxtNumeroLista.setEnabled(false);
        jtxtNumeroReservaP.setEnabled(false);
    }
    
    public void LimpirCampos(){
        
        jtxtNumeroLista.setText("");
        jtxtNumeroReservaP.setText("");
        jtxtNombreClienteP.setText("");
        jtxtEdadClienteP.setText("");
        comboActividadParticipantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Ninguno", "Activo", "Inactivo"}));
        comboEstadoTransporteP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Ninguno","Transporte Propio", "Transporte Contratado"}));
        comboEstadoParticipantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Ninguno", "Pago Pendiente", "Pago Realizado"}));
        
    }
    
    public void obtenerDatos(){
        List<Participantes> participantes = new DAOParticipantes().ObtenerDatos(WIDTH);
        
        DefaultTableModel modelo = new DefaultTableModel();
        
        String [] columnas = {"Nº Lista", "Nombre", "Edad", "Actividad", "Transporte", "Estado Deposito"};
        
        modelo.setColumnIdentifiers(columnas);
        
        for(Participantes pr : participantes){
            String[] renglon = {Integer.toString(pr.getNumero_list()), pr.getNombre_part(),Integer.toString(pr.getEdad_part()),
            pr.getEstado_part(), pr.getEstado_transporte(), pr.getEstado_deposito()};
            
            modelo.addRow(renglon);
        }
        jtableClientesRegistrados.setModel(modelo);
    }
    
    public void actualizarParticipantes(){
        int numL = Integer.parseInt(this.jtxtNumeroLista.getText());
        String nomp = this.jtxtNombreClienteP.getText();
        String edp = this.comboEstadoTransporteP.getSelectedItem().toString();
        String actv = this.comboActividadParticipantes.getSelectedItem().toString();
        String ed = this.comboEstadoParticipantes.getSelectedItem().toString();
        int edadPart = Integer.parseInt(this.jtxtEdadClienteP.getText());
        
        DAOParticipantes dao = new DAOParticipantes();
        
        int res = dao.Actualizar(WIDTH, nomp, edp, edp, TITLE_PROPERTY, edadPart);
        
        if(res == 1){
            JOptionPane.showMessageDialog(rootPane, "Participante Actualizado.");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Lo sentimos. Ocurrio un ERROR");
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtNumeroLista = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtNombreClienteP = new javax.swing.JTextField();
        comboEstadoTransporteP = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboActividadParticipantes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtEdadClienteP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtNumeroReservaP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        comboEstadoParticipantes = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnAgregarReserva = new javax.swing.JButton();
        btnEditarReserva = new javax.swing.JButton();
        btnActualizarReserva = new javax.swing.JButton();
        btnBorrarReserva = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableClientesRegistrados = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Participantes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Nº Lista");

        jtxtNumeroLista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Nombre Cliente");

        jtxtNombreClienteP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        comboEstadoTransporteP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Transporte Propio", "Transporte Contratado" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Estado de transporte");

        comboActividadParticipantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Activo", "Inactivo" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Actividad");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Estado Deposito");

        jtxtEdadClienteP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Edad");

        jtxtNumeroReservaP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Nº Reserva");

        comboEstadoParticipantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Pago Pendiente", "Pago Realizado" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(comboActividadParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboEstadoParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboEstadoTransporteP, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtxtNombreClienteP, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(45, 45, 45)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtxtEdadClienteP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtNumeroLista, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtNumeroReservaP, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNumeroLista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jtxtNumeroReservaP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtNombreClienteP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtEdadClienteP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGap(30, 30, 30)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboEstadoTransporteP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboActividadParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEstadoParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        btnAgregarReserva.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAgregarReserva.setText("Agregar");
        btnAgregarReserva.setPreferredSize(new java.awt.Dimension(79, 23));
        btnAgregarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarReservaActionPerformed(evt);
            }
        });

        btnEditarReserva.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditarReserva.setText("Editar");
        btnEditarReserva.setPreferredSize(new java.awt.Dimension(79, 23));
        btnEditarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarReservaActionPerformed(evt);
            }
        });

        btnActualizarReserva.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnActualizarReserva.setText("Actualizar");
        btnActualizarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarReservaActionPerformed(evt);
            }
        });

        btnBorrarReserva.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBorrarReserva.setText("Borrar");
        btnBorrarReserva.setPreferredSize(new java.awt.Dimension(79, 23));
        btnBorrarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBorrarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                .addComponent(btnActualizarReserva)
                .addGap(18, 18, 18)
                .addComponent(btnEditarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnEditarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnAgregarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBorrarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnActualizarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes Registrados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        jtableClientesRegistrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4", "Título 5", "Título 6", "Título 7"
            }
        ));
        jScrollPane2.setViewportView(jtableClientesRegistrados);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarReservaActionPerformed
        // TODO add your handling code here:
        String nomb = jtxtNombreClienteP.getText();
        String estTrans = comboEstadoTransporteP.getSelectedItem().toString();
        String act = comboActividadParticipantes.getSelectedItem().toString();
        String estDepo = comboEstadoParticipantes.getSelectedItem().toString();
        String edad = jtxtEdadClienteP.getText();
        
        if(nomb.contentEquals("")||edad.contentEquals("")||estTrans.contentEquals("")||
                act.contentEquals("")||estDepo.contentEquals("")){
            JOptionPane.showMessageDialog(rootPane, "No se realizo ningun cambio.");
        }else{
            try {
                int edadP = Integer.valueOf(edad);
                String estadoT = comboEstadoTransporteP.getSelectedItem().toString();
                String actividad = comboActividadParticipantes.getSelectedItem().toString();
                String estadoDepo = comboEstadoParticipantes.getSelectedItem().toString();
                
                
                Participantes pts = new DAOParticipantes().Insertar(nomb, estadoT, estadoDepo, estadoDepo, edadP);
                JOptionPane.showMessageDialog(rootPane, "Registro agregado.");
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "No se agrego el registro.");
            }
        }
        obtenerDatos();
        LimpirCampos();
    }//GEN-LAST:event_btnAgregarReservaActionPerformed

    private void btnEditarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarReservaActionPerformed
        // TODO add your handling code here:
        int fila = this.jtableClientesRegistrados.getSelectedRow();
        
        if(fila == -1){
            JOptionPane.showMessageDialog(rootPane, "Seleccione un participante de la tabla.");
        }else{
            try {
                int numList = Integer.parseInt((String) this.jtableClientesRegistrados.getValueAt(fila, 0));
                String nomP = (String) this.jtableClientesRegistrados.getValueAt(fila, 1);
                int edadPart = Integer.parseInt((String) this.jtableClientesRegistrados.getValueAt(fila,2));
                String estT = this.jtableClientesRegistrados.getValueAt(fila,3).toString();
                String acti = this.jtableClientesRegistrados.getValueAt(fila,4).toString();
                String estDepo = this.jtableClientesRegistrados.getValueAt(fila,5).toString();
                
                jtxtNumeroLista.setText("" + numList);
                jtxtNombreClienteP.setText(nomP);
                jtxtEdadClienteP.setText(String.valueOf(edadPart));
                comboEstadoTransporteP.setSelectedItem(String.valueOf(estT));
                comboActividadParticipantes.setSelectedItem(String.valueOf(acti));
                comboEstadoParticipantes.setSelectedItem(String.valueOf(estDepo));
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnEditarReservaActionPerformed

    private void btnActualizarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarReservaActionPerformed
        // TODO add your handling code here:
        actualizarParticipantes();
        obtenerDatos();
        LimpirCampos();
    }//GEN-LAST:event_btnActualizarReservaActionPerformed

    private void btnBorrarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarReservaActionPerformed
        // TODO add your handling code here:
        int fila = this.jtableClientesRegistrados.getSelectedRow();
        
        if(fila == -1){
            JOptionPane.showMessageDialog(rootPane, "Seleccione un participante de la tabla.");
        }else{
            int num = Integer.parseInt((String) this.jtableClientesRegistrados.getValueAt(fila,0));
            
            DAOParticipantes dao = new DAOParticipantes();
            dao.Eliminar(num);
            obtenerDatos();
        }
    }//GEN-LAST:event_btnBorrarReservaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarReserva;
    private javax.swing.JButton btnAgregarReserva;
    private javax.swing.JButton btnBorrarReserva;
    private javax.swing.JButton btnEditarReserva;
    private javax.swing.JComboBox<String> comboActividadParticipantes;
    private javax.swing.JComboBox<String> comboEstadoParticipantes;
    private javax.swing.JComboBox<String> comboEstadoTransporteP;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jtableClientesRegistrados;
    private javax.swing.JTextField jtxtEdadClienteP;
    private javax.swing.JTextField jtxtNombreClienteP;
    private javax.swing.JTextField jtxtNumeroLista;
    private javax.swing.JTextField jtxtNumeroReservaP;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
