CREATE DATABASE Tuor_OperadoraPT

USE Tuor_OperadoraPT

CREATE TABLE [CLIENTE] (
  [ID_CLIENTE] INT PRIMARY KEY IDENTITY(1,1),
  [NOMBRE_C1] VARCHAR(15),
  [NOMBRE_C2] VARCHAR(15),
  [APELLIDO_C1] VARCHAR(15),
  [APELLIDO_C2] VARCHAR(15),
  [FECHANAC_C] DATE,
  [DEPART_C] VARCHAR(40),
)
GO

CREATE TABLE [RESERVAS] (
  [N_RESERVA] INT PRIMARY KEY IDENTITY(1,1),
  [FECHA_RESERVA] DATE,
  [ID_GIRA] INT,
  [ID_CLIENTE] INT,
)
GO

CREATE TABLE [PARTICIPANTES] (
  [NUMERO_LIST] INT PRIMARY KEY IDENTITY(1,1),
  [NOMBRE_PART1] VARCHAR(15),
  [NOMBRE_PART2] VARCHAR(15),
  [ESTADO_P] VARCHAR(20),
  [ESTADO_DEPO] VARCHAR(20),
  [ESTADO_TRANSP]VARCHAR(20),
  [FECHANAC_PART] DATE,
  [N_RESERVA] INT,
)
GO

CREATE TABLE [GIRAS] (
  [ID_GIRA] INT PRIMARY KEY IDENTITY(1,1),
  [NOMBRE_GIRA] VARCHAR(30),
  [PRECIO_GIRA] FLOAT,
  [DISTANCIA_GIRA] FLOAT,
  [FECHA_GIRA] DATE,
  [ID_EMPLEADO] INT,
)
GO

CREATE TABLE [EMPLEADOS] (
  [ID_EMPLEADO] INT PRIMARY KEY IDENTITY(1,1),
  [NOMBRE_EMP1] VARCHAR(15),
  [NOMBRE_EMP2] VARCHAR(15),
  [APELLIDO_EMP1] VARCHAR(15),
  [APELLIDO_EMP2] VARCHAR(15),
  [DEPART_EMP] VARCHAR(30),
  [TELEFONO_EMP] VARCHAR(15),
  [FECHANAC_EMP] DATE,
)
GO

ALTER TABLE [RESERVAS] ADD FOREIGN KEY ([ID_GIRA]) REFERENCES [GIRAS] ([ID_GIRA]) ON DELETE CASCADE
GO

ALTER TABLE [GIRAS] ADD FOREIGN KEY ([ID_EMPLEADO]) REFERENCES [EMPLEADOS] ([ID_EMPLEADO]) ON DELETE CASCADE
GO

ALTER TABLE [RESERVAS] ADD FOREIGN KEY ([ID_CLIENTE]) REFERENCES [CLIENTE] ([ID_CLIENTE]) ON DELETE CASCADE
GO

ALTER TABLE [PARTICIPANTES] ADD FOREIGN KEY ([N_RESERVA]) REFERENCES [RESERVAS] ([N_RESERVA]) ON DELETE CASCADE
GO